---

- name: Include gpsd install plays
  include: gpsd_service.yml

- name: Include gpsd python binding plays
  include: gpsd_python_binding.yml
  when: install_python_binding

- name: Test GPS data access (with python)
  include: gps_data_check.yml
  when: run_gps_data_check and install_python_binding
